<a href="https://colab.research.google.com/github/lavishabhambri/Machine-Learning/blob/master/Feature_Scaling_Coding_Ninjas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from sklearn import preprocessing

In [ ]:
X = np.array([[1, -1, 2],
             [2, 0, 0],
             [0, 1, -1]])

# Scale 

This makes mean = 0 and variance = 1. But this fits the one data only at a time.

In [ ]:
X_scaled = preprocessing.scale(X)

In [ ]:
print(X_scaled.mean(axis = 0))
print(X_scaled.std(axis = 0))

[0. 0. 0.]
[1. 1. 1.]


# Standard Scale

This makes mean = 0 and variance = 1 and can be fit on other data by making the object.

In [ ]:
scaler = preprocessing.StandardScaler()
scaler.fit(X)

StandardScaler()

In [ ]:
X_test = [[1, 1, 0]]
scaler.transform(X_test)

array([[ 0.        ,  1.22474487, -0.26726124]])